# Generated by Django 3.2.20 on 2026-05-24 16:47

import bson.objectid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(blank=True, help_text='Optional. Defaults to email.', max_length=150, null=True, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('other', 'Other')], default='admin', max_length=32)),
                ('agent_name', models.CharField(blank=True, default='Lindiwe', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('voicelink_did', models.CharField(blank=True, max_length=20, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('otp_attempts', models.PositiveIntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'api_customuser',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False)),
                ('call_sid', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('direction', models.CharField(blank=True, max_length=16, null=True)),
                ('from_number', models.CharField(blank=True, max_length=32, null=True)),
                ('to_number', models.CharField(blank=True, max_length=32, null=True)),
                ('call_type', models.CharField(blank=True, max_length=50, null=True)),
                ('call_status', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('call_date', models.DateTimeField(blank=True, null=True)),
                ('call_created_at', models.DateTimeField(blank=True, null=True)),
                ('call_end_at', models.DateTimeField(blank=True, null=True)),
                ('call_duration', models.IntegerField(blank=True, null=True)),
                ('call_recording_url', models.URLField(blank=True, max_length=500, null=True)),
                ('call_recording_url_s3', models.URLField(blank=True, max_length=500, null=True)),
                ('recording_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('transcript', djongo.models.fields.JSONField(blank=True, null=True)),
                ('ai_analysis_status', models.CharField(blank=True, max_length=50, null=True)),
                ('ai_analysis_updated_at', models.DateTimeField(blank=True, null=True)),
                ('ai_analysis_error', models.TextField(blank=True, null=True)),
                ('sentiment', models.CharField(blank=True, max_length=32, null=True)),
                ('feedback_given', models.BooleanField(blank=True, null=True)),
                ('issues_raised', djongo.models.fields.JSONField(blank=True, null=True)),
                ('conversation_summary', models.TextField(blank=True, null=True)),
                ('call_notes', models.TextField(blank=True, null=True)),
                ('call_feedback', models.TextField(blank=True, null=True)),
                ('call_rating', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('error_reason', models.TextField(blank=True, null=True)),
                ('dnd_status', models.BooleanField(blank=True, null=True)),
                ('didnt_interact', models.CharField(blank=True, default='no', max_length=10, null=True)),
            ],
            options={
                'db_table': 'api_calls',
            },
        ),
        migrations.CreateModel(
            name='FirozLalani',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('dob', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('support_person', models.CharField(blank=True, max_length=100, null=True)),
                ('appointment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_day', models.CharField(blank=True, max_length=100, null=True)),
                ('time_preference', models.CharField(blank=True, max_length=100, null=True)),
                ('selected_slot', models.CharField(blank=True, max_length=100, null=True)),
                ('call_outcome', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_status', models.CharField(blank=True, max_length=100, null=True)),
                ('message_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'firoz_lalani',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False)),
                ('profile_image', models.URLField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False)),
                ('service_id', djongo.models.fields.GenericObjectIdField()),
                ('prompt_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=True, max_length=250, null=True)),
                ('prompt_text', models.TextField()),
            ],
            options={
                'db_table': 'prompts',
                'unique_together': {('service_id', 'prompt_type')},
            },
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(condition=models.Q(('phone__isnull', False), models.Q(('phone', ''), _negated=True)), fields=('phone',), name='unique_customuser_phone_non_empty'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(condition=models.Q(('voicelink_did__isnull', False), models.Q(('voicelink_did', ''), _negated=True)), fields=('voicelink_did',), name='unique_customuser_voicelink_did'),
        ),
    ]
