# Generated by Django 3.2.20 on 2026-05-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firozlalani',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
