"""
Django settings for instabus_backend project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!=bny@9_ydg4$4a%t^^5c_4y$z5#lg%ext@9$7-!2&u@7+p!3w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
AUTH_USE_DEFAULT_OTP = "620603"
ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'dj_rest_auth',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'dj_rest_auth.registration',
    'corsheaders',
    'channels',  # Django Channels for WebSocket support
    'rest_framework_simplejwt.token_blacklist',  # Required for refresh token rotation
    'api',
    'voice_agent',  # Voice Agent app for Exotel WebSocket and voice processing
]

SITE_ID = 1

# Custom user model (replaces django.contrib.auth.models.User)
AUTH_USER_MODEL = 'api.CustomUser'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # Must be at the top
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware', # Critical for security
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'instabus_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'instabus_backend.wsgi.application'

# ASGI Application (for WebSocket support)
ASGI_APPLICATION = 'instabus_backend.asgi.application'

# Channels Configuration
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',  # For development
        # For production, use Redis:
        # 'BACKEND': 'channels_redis.core.RedisChannelLayer',
        # 'CONFIG': {
        #     "hosts": [('127.0.0.1', 6379)],
        # },
    },
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import os
from urllib.parse import quote_plus

# Helper to read config.properties and fallback to Environment Variables
def load_config():
    config = {}
    config_path = BASE_DIR / 'config.properties'
    
    # 1. Try loading from config.properties
    if config_path.exists():
        try:
            with open(config_path, 'r') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#'):
                        try:
                            key, value = line.split('=', 1)
                            config[key.strip()] = value.strip()
                        except ValueError:
                            pass
        except Exception:
            pass
            
    # 2. Add Environment Variables (they override config.properties)
    # This ensures deployment works even if config.properties is missing
    for key, value in os.environ.items():
        config[key] = value
        
    return config

config = load_config()

# Read from config with defaults
MONGO_URI = config.get('MONGO_URI', 'mongodb://root:example@localhost:27017/')
DB_NAME = config.get('DB_NAME', 'instabus_db')

# Make MONGO settings available for voice_agent
MONGO_DATABASE = DB_NAME

# Twilio Configuration
TWILIO_ACCOUNT_SID = config.get('TWILIO_ACCOUNT_SID', '')
TWILIO_API_KEY = config.get('TWILIO_API_KEY', '')
TWILIO_API_SECRET = config.get('TWILIO_API_SECRET', '')
TWILIO_APP_SID = config.get('TWILIO_APP_SID', '')
TWILIO_AUTH_TOKEN  = config.get('TWILIO_AUTH_TOKEN', '')
TWILIO_PHONE_NUMBER = config.get('TWILIO_PHONE_NUMBER', '')


# Gemini API Configuration
GEMINI_API_KEY = config.get('GEMINI_API_KEY', '')
GEMINI_PROVIDER = config.get('GEMINI_PROVIDER', 'vertex').strip().lower()

# Vertex AI Configuration
VERTEX_AI_PROJECT_ID = config.get('VERTEX_AI_PROJECT_ID', '')
VERTEX_AI_LOCATION = config.get('VERTEX_AI_LOCATION', 'us-central1')
VERTEX_AI_MODEL_ID = config.get('VERTEX_AI_MODEL_ID', 'gemini-live-2.5-flash-native-audio')
GOOGLE_CREDENTIALS_JSON = config.get('GOOGLE_CREDENTIALS_JSON', '')

# Model ID mapped for both providers
GEMINI_MODEL_ID = config.get('GEMINI_MODEL_ID', VERTEX_AI_MODEL_ID).strip()

# GoHighLevel / LeadConnector API Key
GHL_API_KEY = config.get('GHL_API_KEY', '').strip()


# Audio Preprocessing
AUDIO_VAD_ENABLED = config.get('AUDIO_VAD_ENABLED', 'false').lower() == 'true'
AUDIO_VAD_AGGRESSIVENESS = int(config.get('AUDIO_VAD_AGGRESSIVENESS', '2'))
AUDIO_VAD_ONSET_FRAMES = int(config.get('AUDIO_VAD_ONSET_FRAMES', '3'))
AUDIO_VAD_HANGOVER_FRAMES = int(config.get('AUDIO_VAD_HANGOVER_FRAMES', '8'))
# RNNoise pre-upsampling denoiser (optional)
AUDIO_RNNOISE_PRE_UP_ENABLED = config.get('AUDIO_RNNOISE_PRE_UP_ENABLED', 'false').lower() == 'true'
# Denoiser engine: 'none' | 'silero'
AUDIO_DENOISE_ENGINE = config.get('AUDIO_DENOISE_ENGINE', 'none')
# Chunk size (ms) to run denoiser on (streaming chunk). Default 800ms
AUDIO_DENOISE_CHUNK_MS = int(config.get('AUDIO_DENOISE_CHUNK_MS', '800'))
AUDIO_NS_LEVEL = int(config.get('AUDIO_NS_LEVEL', '3'))
AUDIO_AGC_ENABLED = config.get('AUDIO_AGC_ENABLED', 'true').lower() == 'true'

# Webhook Base URL
WEBHOOK_BASE_URL = config.get('WEBHOOK_BASE_URL', 'http://localhost:8000')

# OTP Authentication Configuration (dev-first; replace with provider integration later)
AUTH_OTP_EXPIRY_MINUTES = int(config.get('AUTH_OTP_EXPIRY_MINUTES', '5'))
AUTH_DEFAULT_OTP = (config.get('AUTH_DEFAULT_OTP', '620603') or '620603').strip()
AUTH_USE_DEFAULT_OTP = config.get('AUTH_USE_DEFAULT_OTP', 'true').lower() == 'true'
AUTH_OTP_MAX_ATTEMPTS = int(config.get('AUTH_OTP_MAX_ATTEMPTS', '5'))


REDIS_HOST = config.get('REDIS_HOST', '').strip()
REDIS_PORT = config.get('REDIS_PORT', '6379').strip()
REDIS_PASSWORD = config.get('REDIS_PASSWORD', '').strip()
REDIS_DB = config.get('REDIS_DB', '0').strip()
REDIS_URL = (config.get('REDIS_URL', '') or '').strip()
if not REDIS_URL:
    if REDIS_PASSWORD:
        REDIS_URL = f"redis://:{quote_plus(REDIS_PASSWORD)}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"
    else:
        REDIS_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"

# Use Redis Channel Layer dynamically if Redis is configured
if REDIS_HOST or config.get('REDIS_URL'):
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [REDIS_URL],
            },
        },
    }


SCHEDULED_CALLS_INTERNAL_SECRET = config.get('SCHEDULED_CALLS_INTERNAL_SECRET', 'Instabus@1234').strip()
EVENTBRIDGE_BUS_ARN = config.get('EVENTBRIDGE_BUS_ARN', 'arn:aws:events:eu-north-1:035949051123:event-bus/default').strip()
EVENTBRIDGE_SCHEDULER_ROLE_ARN = config.get('EVENTBRIDGE_SCHEDULER_ROLE_ARN', 'arn:aws:iam::035949051123:role/EventBridgeSchedulerRole').strip()
SCHEDULED_CALLS_EVENT_SOURCE = config.get('SCHEDULED_CALLS_EVENT_SOURCE', 'custom.instabus.scheduled_calls').strip()
SCHEDULED_CALLS_DETAIL_TYPE = config.get('SCHEDULED_CALLS_DETAIL_TYPE', 'ScheduledOutboundCall').strip()
SCHEDULED_PRE_TRAVEL_LEAD_MINUTES = int(config.get('SCHEDULED_PRE_TRAVEL_LEAD_MINUTES', '60'))
SCHEDULED_DURING_TRAVEL_POSITION_PERCENT = int(config.get('SCHEDULED_DURING_TRAVEL_POSITION_PERCENT', '50'))
SCHEDULED_FEEDBACK_DELAY_MINUTES = int(config.get('SCHEDULED_FEEDBACK_DELAY_MINUTES', '0'))
# Seconds to wait after a no-answer/busy scheduled dial before the one automatic retry (default 5 minutes).
SCHEDULED_CALL_RETRY_DELAY_SECONDS = int(config.get('SCHEDULED_CALL_RETRY_DELAY_SECONDS', '300'))
# Redis TTL for ib:schedcall:call_status:{call_sid} (mirrors Mongo call status for workers / fast reads).
SCHEDULED_CALL_STATUS_CACHE_TTL_SECONDS = int(config.get('SCHEDULED_CALL_STATUS_CACHE_TTL_SECONDS', '86400'))
# Seconds after scheduled_at_utc before clear_overdue_in_flight may run (ringing + WS-url + webhook latency).
# Default 300 avoids releasing the single-lane lock the instant the slot fires while status is still "queued".
SCHEDULED_CALL_WEBHOOK_GRACE_SECONDS = int(config.get('SCHEDULED_CALL_WEBHOOK_GRACE_SECONDS', '300'))
# After add-lead, if call stays queued/pending (no VoiceLink status webhook / network loss) for this many
# seconds, force-clear in_flight so the worker can continue. Attempt 1 also gets one delayed retry. 0 = disable.
SCHEDULED_CALL_STALE_QUEUED_MAX_AGE_SECONDS = int(
    config.get('SCHEDULED_CALL_STALE_QUEUED_MAX_AGE_SECONDS', '300')
)
AWS_SCHEDULER_ACCESS_KEY_ID = config.get('AWS_SCHEDULER_ACCESS_KEY_ID', '').strip()
AWS_SCHEDULER_SECRET_ACCESS_KEY = config.get('AWS_SCHEDULER_SECRET_ACCESS_KEY', '').strip()
AWS_SCHEDULER_REGION = config.get('AWS_SCHEDULER_REGION', config.get('AWS_REGION', 'us-east-1')).strip()

# WhatsApp template API (scheduled notifications)
WHATSAPP_TEMPLATE_URL = config.get('WHATSAPP_TEMPLATE_URL', 'https://whatsapp.instabus.co.in/api/templates/send').strip()
WHATSAPP_API_KEY = config.get('WHATSAPP_API_KEY', '').strip()
WHATSAPP_TEMPLATE_LANGUAGE_CODE = config.get('WHATSAPP_TEMPLATE_LANGUAGE_CODE', 'en').strip()
WHATSAPP_TEMPLATE_NAME_PRE_TRAVEL = config.get('WHATSAPP_TEMPLATE_NAME_PRE_TRAVEL', 'pre_trevel').strip()
WHATSAPP_TEMPLATE_NAME_DURING_TRAVEL = config.get('WHATSAPP_TEMPLATE_NAME_DURING_TRAVEL', 'during_travel').strip()
WHATSAPP_TEMPLATE_NAME_FEEDBACK = config.get('WHATSAPP_TEMPLATE_NAME_FEEDBACK', 'feedback').strip()
WHATSAPP_TEMPLATE_DEBUG = config.get('WHATSAPP_TEMPLATE_DEBUG', 'false').strip().lower() == 'true'

# AWS S3 Configuration
AWS_ACCESS_KEY_ID = config.get('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = config.get('AWS_SECRET_ACCESS_KEY', '')
AWS_BUCKET_NAME = config.get('AWS_BUCKET_NAME', '')
AWS_REGION = config.get('AWS_REGION', 'us-east-1')

DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': DB_NAME,
        'ENFORCE_SCHEMA': False,
        'CLIENT': {
            'host': MONGO_URI,
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- REST FRAMEWORK CONFIG ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'api.jwt_auth.CustomUserJWTAuthentication', 
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'dj_rest_auth.jwt_auth.JWTCookieAuthentication', 
    ),
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
}

# --- JWT & COOKIE CONFIG (The Security Part) ---
REST_AUTH = {
    "PASSWORD_CHANGE_SERIALIZER": "api.serializers.CustomPasswordChangeSerializer",
    'USE_JWT': True,
    'JWT_AUTH_COOKIE': 'my-app-auth',          # Name of the access token cookie
    'JWT_AUTH_REFRESH_COOKIE': 'my-app-refresh', # Name of the refresh token cookie
    'JWT_AUTH_HTTPONLY': True,                 # Makes sure JS cannot read the cookie
    'SESSION_LOGIN': False,                    # Turn off session login to use JWTs only
}

from datetime import timedelta
SIMPLE_JWT = {
    # 'ACCESS_TOKEN_LIFETIME': timedelta(minutes=150),
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    # CustomUser uses _id (ObjectId) as primary key, not id
    'USER_ID_FIELD': '_id',
}

# --- CORS CONFIG ---
# In production, specify your actual domain.
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173", 
    "http://127.0.0.1:5173",
]
CORS_ALLOW_CREDENTIALS = True # Important: allows cookies to be sent cross-origin
CORS_ALLOW_ALL_ORIGINS = True # Set to True for development - CHANGE IN PRODUCTION
CORS_ALLOWED_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# CSRF Configuration
CSRF_TRUSTED_ORIGINS = ["http://localhost:5173"]
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read CSRF token
CSRF_COOKIE_SAMESITE = 'Lax'

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'clean': {
            'format': '%(asctime)s %(levelname)-8s %(message)s',
            'datefmt': '%b %d %H:%M:%S',  # Feb 09 17:00:25
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'clean',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}
